#!/bin/sh
set -e

# Set proper permissions
chmod o= /etc/dovecot/dovecot-loadbalancer.conf

# Debian helpers
#DEBHELPER#

# Quirk
case "$1" in
  'configure')
     if test -n "$2" && dpkg --compare-versions "$2" lt "3" && service dovecot-loadbalancer status >/dev/null; then
       # Restart the service after init/systemd upgrade/migration
       service dovecot-loadbalancer restart || true
     fi
     ;;
esac

exit 0
